Add commonjs support to hyperdrive-wasm
delvtech/hyperdrive-frontend pull request #1644
Opened 2024-11-11 22:35 UTC by sentilesdal

Hardhat (among other packages) are still using commonjs so if we want to be able to use hyperdrive-wasm with these tool we need to add cjs support.  I've added a basic build to the hyperdrive-wasm package that gets us both a cjs build and an esm build.

- add cjs compat to hyperdrive-wasm
- don't modify the package.json of output dir

2024-11-11 22:46 UTC, ryangoree requested changes
The [`wasm-pack` cli used in the crate's build script](https://github.com/delvtech/hyperdrive-frontend/blob/7a034fc61108de7a008304e90342aace56bd3ea6/crates/hyperdrive-wasm/scripts/build.ts#L67) will blow away the old package when it builds a new one. The entire package is codegen so any changes have to made to the crate itself.

2024-11-11 22:46 UTC, ryangoree commented on crates/hyperdrive-wasm/scripts/build.ts
> -    );
This will still be needed since the file is deleted.

2024-11-11 22:46 UTC, ryangoree commented on crates/hyperdrive-wasm/scripts/build.ts
> -    packageJson.publishConfig = { access: "public" };
This will still be needed for [changesets](https://github.com/delvtech/hyperdrive-frontend#creating-a-release)

2024-11-13 21:02 UTC, sentilesdal commented
closing in favor of #1649

2024-11-13 21:02 UTC, closed without merging